In [2]:
import numpy as np

# Array Defining

In [5]:
xy=np.array([1,2,3,4])
xy

array([1, 2, 3, 4])

# Using ndim

In [6]:
print(xy.ndim)

1


# 1 dimensional 

In [7]:
xy=np.array([1,2,3,4])
print(xy.ndim)

1


In [4]:
a=np.array([[1,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])
print(a.ndim)

2


In [5]:
print(a)

[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]


In [6]:
b=np.array([[[1,2],[45,47],[4,5],[1,2]]])
print(b)
print(b.ndim)

[[[ 1  2]
  [45 47]
  [ 4  5]
  [ 1  2]]]
3


# Zero dimensional

In [8]:
xy=np.array(12)
print(xy.ndim)

0


# DataType

In [9]:
xy=np.array([[1,2,3],[4,5,6]])
print(xy.dtype)

int32


# Length of array

In [10]:
xy=np.array([[1,2,3],[4,5,6]])
len(xy)

2

# Array Iterating

In [11]:
xy=np.array([[1,2,3],[4,5,6]])
for w in xy:
    print(w)

[1 2 3]
[4 5 6]


In [12]:
xy=np.array([[1,2,3],[4,5,6]])
for w in xy:
    for z in w:
        print(z)

1
2
3
4
5
6


# Array Shape

In [13]:
xy=np.array([[1,2,3],[4,5,6]])
print(xy.ndim)
xy.shape

2


(2, 3)

In [8]:
b=np.array([[[1,2],[45,47],[4,5],[1,2]]])
print(b)
print(b.ndim)
print(b.shape)

[[[ 1  2]
  [45 47]
  [ 4  5]
  [ 1  2]]]
3
(1, 4, 2)


In [7]:
b=np.array([[1,2],[45,47],[4,5],[1,2]])
print(b)
print(b.ndim)
print(b.shape)

[[ 1  2]
 [45 47]
 [ 4  5]
 [ 1  2]]
2
(4, 2)


In [9]:
b=np.array([[[[[1,2],[45,47],[4,5],[1,2]]]]])
print(b)
print(b.ndim)
print(b.shape)

[[[[[ 1  2]
    [45 47]
    [ 4  5]
    [ 1  2]]]]]
5
(1, 1, 1, 4, 2)


# Array Reshaping

In [14]:
xy=np.array([[1,2,3],[4,5,6]])
xy1=xy.reshape(1,2,3)
xy1

array([[[1, 2, 3],
        [4, 5, 6]]])

# Array Spliting

In [21]:
xy=np.array([[1,2,3],[4,5,6]])
xy1=np.array_split(xy,2)
xy1

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [22]:
xy=np.array([[1,2],[4,5],[8,9]])
xy1=np.array_split(xy,10)
xy1

[array([[1, 2]]),
 array([[4, 5]]),
 array([[8, 9]]),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32),
 array([], shape=(0, 2), dtype=int32)]

In [23]:
xy=np.array([1,2,3,4,5,6])
xy1=np.array_split(xy,10)
xy1

[array([1]),
 array([2]),
 array([3]),
 array([4]),
 array([5]),
 array([6]),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32),
 array([], dtype=int32)]

# Array Searching

In [11]:
xy=np.array([1,2,3,4,5,6])
xy1=np.where(xy>=2)
xy1

(array([1, 2, 3, 4, 5], dtype=int64),)

In [25]:
xy=np.array([1,2,3,4,5,6])
xy1=np.where(xy%2==0)
xy1

(array([1, 3, 5], dtype=int64),)

In [26]:
xy=np.array([1,2,3,4,5,6])
xy1=np.where(xy%2==1)
xy1

(array([0, 2, 4], dtype=int64),)

# Array Joining

In [27]:
xy1=np.array([1,2,3,4,5,6])
xy2=np.array([7,8,9,10,11,12])
xy3=np.concatenate((xy1,xy2))
xy3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [28]:
xy1=np.array([[1,2,3],[4,5,6]])
xy2=np.array([[7,8,9,],[11,12,13]])
xy3=np.concatenate((xy1,xy2),axis=1)
xy3

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 11, 12, 13]])

In [29]:
xy1=np.array([[1,2,3],[4,5,6]])
xy2=np.array([[7,8,9,],[11,12,13]])
xy3=np.concatenate((xy1,xy2))
xy3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

# Array sorting

In [30]:
xy=np.array([2,5,1,7,8,5])
xy1=np.sort(xy)
xy1

array([1, 2, 5, 5, 7, 8])

In [31]:
xy=np.array([2,5,1,7,8,5])
xy1=-np.sort(-xy)
xy1

array([8, 7, 5, 5, 2, 1])

In [2]:
import numpy as np

In [9]:
xy4=np.array([2,1,7,8,5,5])
xy5=np.sort(xy4)
xy5

array([1, 2, 5, 5, 7, 8])

In [10]:
xy6=np.flip(xy5)
xy6

TypeError: flip() missing 1 required positional argument: 'axis'

# Array Filtering

In [36]:
xy=np.array([2,1,7,8])
xy1=[True,False,True,False]
new=xy[xy1]
new

array([2, 7])

In [37]:
xy=np.array([2,1,7,8])
xy1=[False,True,False,True]
new=xy[xy1]
new

array([1, 8])

In [40]:
new=[]
xy=np.array([20,10,70,80])
for x in xy:
    if x>=10:
        new.append(True)
    else:
        new.append(False)
new

[True, True, True, True]

In [41]:
new=[]
xy=np.array([20,10,70,80])
for x in xy:
    if x>10:
        new.append(True)
    else:
        new.append(False)
new

[True, False, True, True]