# Numpy functions(Splitting, Searching, Joining, Sorting, Filttering)

In [2]:
import numpy as np

In [96]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array_split(a,3)
b

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([], shape=(0, 3), dtype=int32)]

In [3]:
a=np.array([[1,2,3],[4,6,7]])
a1=np.array_split(a,3)
a1

[array([[1, 2, 3]]), array([[4, 6, 7]]), array([], shape=(0, 3), dtype=int32)]

In [4]:
a=np.array([[1,2,3],[4,6,7]])
a1=np.array_split(a,2)
a1

[array([[1, 2, 3]]), array([[4, 6, 7]])]

In [100]:
a=np.array([[1,2,3,4,5,6]])
b=np.where(a>=2)
b

(array([0, 0, 0, 0, 0], dtype=int64), array([1, 2, 3, 4, 5], dtype=int64))

In [5]:
a=np.array([[1,2,3],[4,6,7]])
a1=np.where(a>=2)
a1

(array([0, 0, 1, 1, 1], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [6]:
a=np.array([1,2,3,4,6,7])
a1=np.where(a%2==0)
a1

(array([1, 3, 4], dtype=int64),)

In [102]:
p=np.array([1,2,3,4])
q=np.array([5,6,7,8])
q=np.concatenate((p,q))
q

array([1, 2, 3, 4, 5, 6, 7, 8])

In [105]:
p=np.array([[1,2,3,4]])
q=np.array([[5,6,7,8]])
r=np.concatenate((p,q),axis=1)
r

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [7]:
a=np.array([1,2,3,4,6,7])
b=np.array([8,9,10,11,12,13])
c=np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  6,  7,  8,  9, 10, 11, 12, 13])

In [8]:
a=np.array([[1,2,3,4,6,7],[1,2,3,4,6,7]])
b=np.array([[8,9,10,11,12,13],[8,9,10,11,12,13]])
c=np.concatenate((a,b))
c

array([[ 1,  2,  3,  4,  6,  7],
       [ 1,  2,  3,  4,  6,  7],
       [ 8,  9, 10, 11, 12, 13],
       [ 8,  9, 10, 11, 12, 13]])

In [108]:
a=np.array([4,8,2,5,3,9,7,1,6])
b=np.sort(a)
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a=np.array([2,4,1,6,3,7,5])
a1=np.sort(a)
a1

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
a2=-np.sort(-a1)
a2

array([7, 6, 5, 4, 3, 2, 1])

In [109]:
c=-np.sort(-b)
c

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [3]:
pq=np.array([1,2,3,4,5,6])
rs=[True,False,True,False]
new=pq[rs]
new

C:\Users\Aniket\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: boolean index did not match indexed array along dimension 0; dimension is 6 but corresponding boolean dimension is 4
  This is separate from the ipykernel package so we can avoid doing imports until


array([1, 3])

In [11]:
x=np.array([2,4,6,5])
x1=[True,False,True,False]
new=x[x1]
new

array([2, 6])

In [12]:
new=[]
x=np.array([2,4,6,5])
for y in x:
    if y>=2:
        new.append(True)
    else:
        new.append(False)
        
new

[True, True, True, True]

In [13]:
new=[]
x=np.array([2,4,6,5])
for y in x:
    if y>=3:
        new.append(True)
    else:
        new.append(False)
        
new

[False, True, True, True]